server:
  port: 8762
eureka:
  instance:
    hostname: eureka2
  client:
#    表示是否注册自身到eureka服务器
#    register-with-eureka: false
#    是否从eureka上获取注册信息
#    fetch-registry: false
    service-url:
      defaultZone: http://admin:admin123@eureka1:8761/eureka/