spring:
  application:
    name: eureka
#  profiles:
#    active: eureka1
  security:
    user:
      name: admin
      password: admin123
      
eureka: 
  instance: 
    instance-id: ${eureka.instance.hostname}:${server.port} 
#    hostname: eureka2
#  client:
#    由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为 false(集群环境需要为true)  
#    fetch-registry: false
#    由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己(集群环境需要为true)
#    register-with-eureka: false
#    serviceUrl:
#      defaultZone: http://admin:admin123@eureka1:8761/eureka/

#自定义log日志输出20201104
logging:
  path: /Users/jackie/workspace/rome/
  file: eureka2.log
  level:
    root: INFO
#指定包下的日志级别
    com:
      jackie:
        springbootdemo:
          config: WARN
#日志输出格式
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}][%thread]%-5level %logger- %msg%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss}][%thread]%-5level %logger- %msg%n"

